package se.umu.cs.gcom.Debugger;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

public class TestView {
    private JTextField createGroupField;
    private JComboBox comTypeBox;
    private JComboBox orderTypeBox;
    private JButton createButton;
    private JButton joinButton1;
    private JList GrouplistField;
    private JLabel createGroupLabel;
    private JLabel communicationLabel;
    private JLabel joinGroupLabel;
    private JTextField joinGroupField;
    private JLabel orderingLabel;
    private JButton removeButton;
    private JPanel userPanel;

    public TestView() {
        userPanel.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                super.componentHidden(e);
            }
        });
    }

    public JTextField getCreateGroupField() {
        return createGroupField;
    }

    public JComboBox getComTypeBox() {
        return comTypeBox;
    }

    public JComboBox getOrderTypeBox() {
        return orderTypeBox;
    }

    public JButton getCreateButton() {
        return createButton;
    }

    public JButton getJoinButton1() {
        return joinButton1;
    }

    public JList getGrouplistField() {
        return GrouplistField;
    }

    public JLabel getCreateGroupLabel() {
        return createGroupLabel;
    }

    public JLabel getCommunicationLabel() {
        return communicationLabel;
    }

    public JLabel getJoinGroupLabel() {
        return joinGroupLabel;
    }

    public JTextField getJoinGroupField() {
        return joinGroupField;
    }

    public JLabel getOrderingLabel() {
        return orderingLabel;
    }

    public JButton getRemoveButton() {
        return removeButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        userPanel = new JPanel();
        userPanel.setLayout(new GridBagLayout());
        createGroupLabel = new JLabel();
        createGroupLabel.setText("Create Group");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        userPanel.add(createGroupLabel, gbc);
        communicationLabel = new JLabel();
        communicationLabel.setText("Communication");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        userPanel.add(communicationLabel, gbc);
        createGroupField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userPanel.add(createGroupField, gbc);
        joinGroupLabel = new JLabel();
        joinGroupLabel.setText("Join Group");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        userPanel.add(joinGroupLabel, gbc);
        joinGroupField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userPanel.add(joinGroupField, gbc);
        orderingLabel = new JLabel();
        orderingLabel.setText("Ordering");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        userPanel.add(orderingLabel, gbc);
        comTypeBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userPanel.add(comTypeBox, gbc);
        orderTypeBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userPanel.add(orderTypeBox, gbc);
        createButton = new JButton();
        createButton.setText("Create");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userPanel.add(createButton, gbc);
        removeButton = new JButton();
        removeButton.setText("Remove");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userPanel.add(removeButton, gbc);
        joinButton1 = new JButton();
        joinButton1.setText("Join");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        userPanel.add(joinButton1, gbc);
        GrouplistField = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        GrouplistField.setModel(defaultListModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.gridheight = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        userPanel.add(GrouplistField, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return userPanel;
    }

}
